[package]
name = "search_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.13.1"
rocksdb = "0.24.0"
scraper = "0.25.0"
tokio = { version = "1", features = ["full"] }

ureq = "3.1.4"
url = "2.5.8"
